index:
    path: /
    controller: 'App\Controller\DefaultController::index'

login:
    path: /login
    controller: 'App\Controller\LoginController::index'

admin:
    path: /admin
    controller: App\Controller\AdminController::index

logout:
    path: /logout