index:
    path: /
    controller: 'App\Controller\DefaultController::index'

login:
    path: /login
    controller: 'App\Controller\LoginController::index'

admin:
    path: /admin
    controller: App\Controller\AdminController::index

logout:
    path: /logout

api.device:
    path: /api/device/{deviceId}
    controller: App\Controller\DeviceApiController::getById
    defaults:
          _format: json

api.devices:
    path: /api/devices
    controller: App\Controller\DeviceApiController::getAll
    defaults:
          _format: json
